env:
  BUILDKITE_ANALYTICS_TOKEN: FA2gLUrPcFzZfgUyEoQnvRAX

steps:
  - label: ":dotnet: :testexecute: Test"
    key: "test"
    command: dotnet test MicroserviceA/MicroserviceA.Tests/MicroserviceA.Tests.csproj --logger "junit;LogFileName=test-results.xml"
    plugins:
      - docker:
          image: mcr.microsoft.com/dotnet/sdk:9.0
      - artifacts:
          upload:
            - "**/test-results.xml"

  - label: "ðŸ” Test Engine"
    depends_on: "test"
    command: buildkite-agent artifact download "**/test-results.xml" .
    plugins:
      - test-collector#v1.11.0:
          files: "**/test-results.xml"
          format: "junit"
  
  - label: ":dotnet: Get affected projects"
    key: "affected"
    depends_on: "test"
    command: |
      # Install jq for JSON parsing
      apt-get update && apt-get install -y jq
    
      dotnet tool restore
      # Store affected projects in a file to be used by later steps
      dotnet affected --format=json --output-name affected-projects --from $BUILDKITE_COMMIT --to master
      
      # Check if any projects are affected
      if [ "$(cat affected-projects.json | jq 'length')" -gt 0 ]; then
        echo "Affected projects found"
        cat affected-projects.json | jq -r '.[]' > affected-list.txt
        echo "true" > has-affected-projects.txt
      else
        echo "No affected projects found"
        echo "[]" > affected-projects.json
        touch affected-list.txt
        echo "false" > has-affected-projects.txt
      fi
    plugins:
      - docker:
          image: mcr.microsoft.com/dotnet/sdk:8.0
          mount-buildkite-agent: true
          user: root
      - artifacts:
          upload:
            - affected-projects.json
            - affected-list.txt
            - has-affected-projects.txt

  - label: ":pipeline: Generate restore/build pipeline"
    key: "pipeline-gen"
    depends_on: "affected"
    command: ".buildkite/scripts/restore.sh"
    plugins:
      - artifacts:
          download:
            - affected-projects.json
            - has-affected-projects.txt