steps:
  - label: ":dotnet: Get affected projects"
    key: "affected"
    command: |
      # Install jq for JSON parsing
      apt-get update && apt-get install -y jq
    
      dotnet tool restore
      # Store affected projects in a file to be used by later steps
      dotnet affected --format=json --output-name affected-projects --from $BUILDKITE_COMMIT --to master
      
      # Check if any projects are affected
      if [ "$(cat affected-projects.json | jq 'length')" -gt 0 ]; then
        echo "Affected projects found"
        cat affected-projects.json | jq -r '.[]' > affected-list.txt
        echo "true" > has-affected-projects.txt
      else
        echo "No affected projects found"
        echo "[]" > affected-projects.json
        touch affected-list.txt
        echo "false" > has-affected-projects.txt
      fi
    plugins:
      - docker:
          image: mcr.microsoft.com/dotnet/sdk:8.0
          mount-buildkite-agent: true
          user: root
      - artifacts:
          upload:
            - affected-projects.json
            - affected-list.txt
            - has-affected-projects.txt

  - label: ":dotnet: Restore dependencies"
    key: "restore"
    depends_on: "affected"
    command: |
        # Install necessary tools
        apt-get update && apt-get install -y jq
    
        # Check if we have any affected projects
        if [ "$(cat has-affected-projects.txt)" = "true" ]; then
          echo "Restoring affected projects"
        
          # Read the affected projects and restore each one
          while read -r project; do
            echo "Restoring $project"
            dotnet restore "$project" --packages .nuget/packages
          done < affected-list.txt
        
          # Create a list of restored projects for reference
          echo "Projects restored:" > restored-projects.txt
          cat affected-list.txt >> restored-projects.txt
        else
          echo "No projects to restore"
          echo "No projects restored" > restored-projects.txt
        fi
    plugins:
      - docker:
          image: mcr.microsoft.com/dotnet/sdk:9.0
      - artifacts:
          download: 
          - affected-list.txt
          - has-affected-projects.txt
      - artifacts:
          upload:
            - .nuget/packages
            - restored-projects.txt
      - artifacts:
          compressed: .nuget/packages.tgz
          upload: .nuget/packages

  - label: ":dotnet: Build"
    command: "dotnet build --configuration Release --no-restore --property:EnforceCodeStyleInBuild=true"
    depends_on: "restore"
    plugins:
      - artifacts:
          download: .nuget/packages
          compressed: .nuget/packages.tgz
      - artifacts:
          download: restored-projects.txt
      - docker:
          image: mcr.microsoft.com/dotnet/sdk:9.0