steps:
  - label: ":dotnet: Restore tools"
    key: "tool_restore"
    command: "dotnet tool restore"
    plugins:
      - docker:
          image: mcr.microsoft.com/dotnet/sdk:9.0
  - label: ":dotnet: Get affected projects"
    depends_on: "tool_restore"
    key: "affected"
    command: "dotnet affected"
    plugins:
      - docker:
          image: mcr.microsoft.com/dotnet/sdk:9.0
  - label: ":dotnet: Restore dependencies"
    command: "dotnet restore MicroserviceA/MicroserviceA.csproj --packages .nuget/packages"
    key: "deps"
    depends_on: "affected"
    plugins:
      - docker:
          image: mcr.microsoft.com/dotnet/sdk:9.0
      - artifacts:
          upload: .nuget/packages
          compressed: .nuget/packages.tgz
      - artifacts:
          upload: MicroserviceA/obj/*

  - label: ":dotnet: Build"
    command: "dotnet build --configuration Release --no-restore --property:EnforceCodeStyleInBuild=true"
    depends_on: "deps"
    plugins:
      - artifacts:
          download: .nuget/packages
          compressed: .nuget/packages.tgz
      - artifacts:
          download: MicroserviceA/obj/*
      - docker:
          image: mcr.microsoft.com/dotnet/sdk:9.0