steps:
  - label: ":dotnet: Restore dependencies"
    command: "dotnet restore MicroserviceA\MicroserviceA.csproj --packages .nuget/packages"
    key: "deps"
    plugins:
      - docker:
          image: mcr.microsoft.com/dotnet/sdk:9.0
      - artifacts:
          upload: .nuget/packages
          compressed: .nuget/packages.tgz
      - artifacts:
          upload: obj/*

  - label: ":dotnet: Build"
    command: "dotnet build --configuration Release --no-restore --property:EnforceCodeStyleInBuild=true"
    depends_on: "deps"
    plugins:
      - artifacts:
          download: .nuget/packages
          compressed: .nuget/packages.tgz
      - artifacts:
          download: obj/*
      - docker:
          image: mcr.microsoft.com/dotnet/sdk:9.0